name: Go

on:
  workflow_dispatch:
  push:
    branches: 
    - $default-branch
    - develop
    - "feature/**"
    
  pull_request:
    branches:
    - $default-branch
    - develop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...
      
    - name: Test
      run: |
        go mod tidy
        go test -v ./...

    - name: Build Artifacts (linux/amd64)
      env:
        GOOS: linux
        GOARCH: amd64
      run: go build -o "dist/bitbucket-webhook-$GOOS-$GOARCH" .        

    - name: Build Artifacts (darwin/amd64)
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -o "dist/bitbucket-webhook-$GOOS-$GOARCH" .  

    - name: Build Artifacts (darwin/amd64)
      env:
        GOOS: darwin
        GOARCH: arm64
      run: go build -o "dist/bitbucket-webhook-$GOOS-$GOARCH" .  
      
    - name: Build Artifacts (windows/amd64)
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -o "dist/bitbucket-webhook-$GOOS-$GOARCH" .  
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.0
      with:
        name: binaries
        path: dist/*
